"""init

迁移 ID: 1b51e394adf2
父迁移: 61fed2e7726a
创建时间: 2026-01-22 13:16:50.686700

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1b51e394adf2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('rssget',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Content',
    sa.Column('id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('time', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('trans_text', sa.String(length=255), nullable=True),
    sa.Column('image_num', sa.String(length=255), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Content')),
    info={'bind_key': 'rssget'}
    )
    op.create_table('Detail',
    sa.Column('id', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Detail')),
    info={'bind_key': 'rssget'}
    )
    op.create_table('Group_config',
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('if_need_trans', sa.BOOLEAN(), nullable=False),
    sa.Column('if_need_self_trans', sa.BOOLEAN(), nullable=False),
    sa.Column('if_need_translate', sa.BOOLEAN(), nullable=False),
    sa.Column('if_need_photo_num_mention', sa.BOOLEAN(), nullable=False),
    sa.Column('if_need_merged_message', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_Group_config')),
    info={'bind_key': 'rssget'}
    )
    op.create_table('Plantform',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('need_trans', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_Plantform')),
    info={'bind_key': 'rssget'}
    )
    op.create_table('Subscribe',
    sa.Column('id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('group', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Subscribe')),
    info={'bind_key': 'rssget'}
    )
    op.create_table('User',
    sa.Column('User_ID', sa.String(length=255), nullable=True),
    sa.Column('User_Name', sa.String(length=255), nullable=True),
    sa.Column('Plantform', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('User_ID', name=op.f('pk_User')),
    info={'bind_key': 'rssget'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Subscribe')
    op.drop_table('Plantform')
    op.drop_table('Group_config')
    op.drop_table('Detail')
    op.drop_table('Content')
    # ### end Alembic commands ###
